{% set name = "pgsanity" %}
{% set version = "0.2.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pgsanity-{{ version }}.tar.gz
  sha256: de0bbd6fe4f98bf5139cb5f466eac2e2abaf5a7b050b9e4867b87bf360873173

build:
  number: 1
  noarch: python
  entry_points:
    - pgsanity = pgsanity.pgsanity:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pgsanity
  commands:
    - pip check
    - pgsanity --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/markdrago/pgsanity
  summary: Check syntax of sql for PostgreSQL
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
